# Generated by Django 5.1.6 on 2025-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('no_of_employee', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('ENTRY', 'Entry'), ('MID', 'Mid'), ('SENIOR', 'Senior'), ('TOP', 'Top')], max_length=20)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote'), ('TRAINEESHIP', 'Traineeship')], max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('offer_type', models.CharField(blank=True, max_length=255)),
                ('salary_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=255)),
                ('currency', models.CharField(choices=[('DOLLAR', 'Dollar'), ('INR', 'Indian Rupee'), ('NRS', 'Nepalese Rupee')], default='NRS', max_length=255)),
                ('minimum_salary', models.PositiveIntegerField()),
                ('maximum_salary', models.PositiveIntegerField(blank=True)),
                ('description', models.TextField()),
                ('hide_salary', models.BooleanField(default=False)),
            ],
        ),
    ]
