# Generated by Django 5.1.6 on 2025-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='offer_type',
            field=models.CharField(choices=[('RANGE', 'Range'), ('FIXED', 'Fixed')], max_length=255),
        ),
    ]
