# Generated by Django 5.1.6 on 2025-02-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employerprofile_company_address_and_more'),
        ('jobs', '0003_job_created_at_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employerprofile'),
        ),
    ]
