# Generated by Django 5.1.6 on 2025-02-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employerprofile_company_address_and_more'),
        ('jobs', '0004_job_deadline_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employerprofile'),
        ),
    ]
