# Generated by Django 5.1.6 on 2025-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseekerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='current_address',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='permanent_address',
            field=models.CharField(blank=True),
        ),
    ]
