# Generated by Django 5.1.6 on 2025-02-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_jobseekerprofile_current_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
    ]
